export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

alias bx='bundle exec'

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export PS1='[vm] \w$(__git_ps1 " (%s)") \$ '
